/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as DocumentationIndexRouteImport } from './../routes/documentation/index'
import { Route as BuilderIndexRouteImport } from './../routes/builder/index'
import { Route as DocumentationSlugIndexRouteImport } from './../routes/documentation/$slug.index'
import { Route as DemandIdIndexRouteImport } from './../routes/demand/$id.index'
import { Route as DiscountingIdMethodIndexRouteImport } from './../routes/discounting/$id.$method.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSlugIndexRoute = DocumentationSlugIndexRouteImport.update({
  id: '/documentation/$slug/',
  path: '/documentation/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandIdIndexRoute = DemandIdIndexRouteImport.update({
  id: '/demand/$id/',
  path: '/demand/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountingIdMethodIndexRoute =
  DiscountingIdMethodIndexRouteImport.update({
    id: '/discounting/$id/$method/',
    path: '/discounting/$id/$method/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/documentation/$slug/': typeof DocumentationSlugIndexRoute
  '/discounting/$id/$method/': typeof DiscountingIdMethodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderIndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/demand/$id': typeof DemandIdIndexRoute
  '/documentation/$slug': typeof DocumentationSlugIndexRoute
  '/discounting/$id/$method': typeof DiscountingIdMethodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/documentation/$slug/': typeof DocumentationSlugIndexRoute
  '/discounting/$id/$method/': typeof DiscountingIdMethodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder/'
    | '/documentation/'
    | '/demand/$id/'
    | '/documentation/$slug/'
    | '/discounting/$id/$method/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/documentation'
    | '/demand/$id'
    | '/documentation/$slug'
    | '/discounting/$id/$method'
  id:
    | '__root__'
    | '/'
    | '/builder/'
    | '/documentation/'
    | '/demand/$id/'
    | '/documentation/$slug/'
    | '/discounting/$id/$method/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  DemandIdIndexRoute: typeof DemandIdIndexRoute
  DocumentationSlugIndexRoute: typeof DocumentationSlugIndexRoute
  DiscountingIdMethodIndexRoute: typeof DiscountingIdMethodIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$slug/': {
      id: '/documentation/$slug/'
      path: '/documentation/$slug'
      fullPath: '/documentation/$slug/'
      preLoaderRoute: typeof DocumentationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/$id/': {
      id: '/demand/$id/'
      path: '/demand/$id'
      fullPath: '/demand/$id/'
      preLoaderRoute: typeof DemandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounting/$id/$method/': {
      id: '/discounting/$id/$method/'
      path: '/discounting/$id/$method'
      fullPath: '/discounting/$id/$method/'
      preLoaderRoute: typeof DiscountingIdMethodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  DemandIdIndexRoute: DemandIdIndexRoute,
  DocumentationSlugIndexRoute: DocumentationSlugIndexRoute,
  DiscountingIdMethodIndexRoute: DiscountingIdMethodIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
