/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscountingIdIndexRouteImport } from './routes/discounting.$id.index'
import { Route as DemandIdIndexRouteImport } from './routes/demand.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountingIdIndexRoute = DiscountingIdIndexRouteImport.update({
  id: '/discounting/$id/',
  path: '/discounting/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandIdIndexRoute = DemandIdIndexRouteImport.update({
  id: '/demand/$id/',
  path: '/demand/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/discounting/$id/': typeof DiscountingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demand/$id': typeof DemandIdIndexRoute
  '/discounting/$id': typeof DiscountingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/discounting/$id/': typeof DiscountingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demand/$id/' | '/discounting/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demand/$id' | '/discounting/$id'
  id: '__root__' | '/' | '/demand/$id/' | '/discounting/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemandIdIndexRoute: typeof DemandIdIndexRoute
  DiscountingIdIndexRoute: typeof DiscountingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounting/$id/': {
      id: '/discounting/$id/'
      path: '/discounting/$id'
      fullPath: '/discounting/$id/'
      preLoaderRoute: typeof DiscountingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/$id/': {
      id: '/demand/$id/'
      path: '/demand/$id'
      fullPath: '/demand/$id/'
      preLoaderRoute: typeof DemandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemandIdIndexRoute: DemandIdIndexRoute,
  DiscountingIdIndexRoute: DiscountingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
