/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation/index'
import { Route as DocumentationSlugIndexRouteImport } from './routes/documentation/$slug.index'
import { Route as DiscountingIdIndexRouteImport } from './routes/discounting.$id.index'
import { Route as DemandIdIndexRouteImport } from './routes/demand.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSlugIndexRoute = DocumentationSlugIndexRouteImport.update({
  id: '/documentation/$slug/',
  path: '/documentation/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountingIdIndexRoute = DiscountingIdIndexRouteImport.update({
  id: '/discounting/$id/',
  path: '/discounting/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandIdIndexRoute = DemandIdIndexRouteImport.update({
  id: '/demand/$id/',
  path: '/demand/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/discounting/$id/': typeof DiscountingIdIndexRoute
  '/documentation/$slug/': typeof DocumentationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/demand/$id': typeof DemandIdIndexRoute
  '/discounting/$id': typeof DiscountingIdIndexRoute
  '/documentation/$slug': typeof DocumentationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/demand/$id/': typeof DemandIdIndexRoute
  '/discounting/$id/': typeof DiscountingIdIndexRoute
  '/documentation/$slug/': typeof DocumentationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation/'
    | '/demand/$id/'
    | '/discounting/$id/'
    | '/documentation/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/demand/$id'
    | '/discounting/$id'
    | '/documentation/$slug'
  id:
    | '__root__'
    | '/'
    | '/documentation/'
    | '/demand/$id/'
    | '/discounting/$id/'
    | '/documentation/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  DemandIdIndexRoute: typeof DemandIdIndexRoute
  DiscountingIdIndexRoute: typeof DiscountingIdIndexRoute
  DocumentationSlugIndexRoute: typeof DocumentationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$slug/': {
      id: '/documentation/$slug/'
      path: '/documentation/$slug'
      fullPath: '/documentation/$slug/'
      preLoaderRoute: typeof DocumentationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounting/$id/': {
      id: '/discounting/$id/'
      path: '/discounting/$id'
      fullPath: '/discounting/$id/'
      preLoaderRoute: typeof DiscountingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand/$id/': {
      id: '/demand/$id/'
      path: '/demand/$id'
      fullPath: '/demand/$id/'
      preLoaderRoute: typeof DemandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  DemandIdIndexRoute: DemandIdIndexRoute,
  DiscountingIdIndexRoute: DiscountingIdIndexRoute,
  DocumentationSlugIndexRoute: DocumentationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
